import type { RegistryItemSchema } from "./types";

export const components: RegistryItemSchema[] = [
	{
		name: "alert",
		module: "@tint-ui/alert",
		withStyles: true,
		registryDependencies: ["svg-icon"],
	},
	{
		name: "app",
		module: "@tint-ui/app",
		registryDependencies: ["trigger"],
		dependencies: ["mobx"],
	},
	{
		name: "avatar",
		module: "@tint-ui/avatar",
		withStyles: true,
		icons: ["user"],
		registryDependencies: ["svg-icon", "trigger"],
	},
	{
		name: "badge",
		module: "@tint-ui/badge",
		withStyles: true,
	},
	{
		name: "breadcrumb",
		module: "@tint-ui/breadcrumb",
		withStyles: true,
		icons: ["chevron-right", "dots"],
		registryDependencies: ["svg-icon"],
	},
	{
		name: "button",
		module: "@tint-ui/button",
		withStyles: true,
		icons: ["loader"],
		registryDependencies: ["svg-icon", "trigger"],
	},
	{
		name: "card",
		module: "@tint-ui/card",
		withStyles: true,
	},
	{
		name: "command",
		module: "@tint-ui/command",
		withStyles: true,
		icons: ["search"],
		registryDependencies: ["svg-icon"],
		dependencies: ["cmdk"],
	},
	{
		name: "data-table",
		module: "@tint-ui/data-table",
		withStyles: true,
		icons: [
			"data-table-row-menu",
			"data-table-boolean-true",
			"data-table-boolean-false",
			"data-table-boolean-null",
			"data-table-view",
			"data-table-view-columns",
			"data-table-view-sorts",
			"data-table-view-filters",
			"data-table-add-filter",
			"pagination-first",
			"pagination-last",
			"pagination-previous",
			"pagination-next",
			"check",
			"dots",
			"search",
			"selector",
			"sort-desc",
			"sort-asc",
			"x",
		],
		registryDependencies: [
			"table",
			"badge",
			"button",
			"command",
			"popover",
			"input",
			"slide-navigator",
			"dropdown-menu",
			"tooltip",
			"trigger",
			"app",
			"svg-icon",
		],
		dependencies: ["@tanstack/react-table"],
	},
	{
		name: "dialog",
		module: "@tint-ui/dialog",
		withStyles: true,
		icons: ["x"],
		registryDependencies: ["svg-icon"],
	},
	{
		name: "dialog-manager",
		module: "@tint-ui/dialog-manager",
		withStyles: true,
		registryDependencies: ["dialog", "trigger"],
		docs: "If you want to use the registrar functions, you also need to include the `app`, `button` and `input` components.",
	},
	{
		name: "dropdown-menu",
		module: "@tint-ui/dropdown-menu",
		withStyles: true,
		registryDependencies: ["svg-icon"],
		icons: ["check", "chevron-right", "circle"],
	},
	{
		name: "form-grid",
		module: "@tint-ui/form-grid",
		withStyles: true,
		registryDependencies: [
			"app",
			"button",
			"svg-icon",
			"trigger",
			"form-input-group",
			"input",
			"input-checkbox",
			"input-select",
			"input-password",
		],
		dependencies: ["react-hook-form", "@hookform/resolvers", "zod"],
		icons: ["x", "plus", "item-collapse", "item-expand", "arrow-down"],
	},
	{
		name: "form-input-group",
		module: "@tint-ui/form-input-group",
		withStyles: true,
		registryDependencies: ["input"],
		dependencies: ["react-hook-form"],
	},
	{
		name: "input",
		module: "@tint-ui/input",
		withStyles: true,
	},
	{
		name: "input-checkbox",
		module: "@tint-ui/input-checkbox",
		withStyles: true,
	},
	{
		name: "input-password",
		module: "@tint-ui/input-password",
		icons: ["eye", "eye-off"],
		registryDependencies: ["svg-icon", "input"],
	},
	{
		name: "input-select",
		module: "@tint-ui/input-select",
		withStyles: true,
		icons: ["x", "selector", "check", "loader"],
		registryDependencies: ["svg-icon", "popover", "command"],
	},
	{
		name: "popover",
		module: "@tint-ui/popover",
		withStyles: true,
	},
	{
		name: "separator",
		module: "@tint-ui/separator",
		withStyles: true,
	},
	{
		name: "slide-navigator",
		module: "@tint-ui/slide-navigator",
		withStyles: true,
		registryDependencies: ["button", "svg-icon"],
		icons: ["chevron-left", "chevron-right"],
	},
	{
		name: "svg-icon",
		module: "@tint-ui/svg-icon",
	},
	{
		name: "table",
		module: "@tint-ui/table",
		withStyles: true,
		icons: ["selector", "sort-asc", "sort-desc"],
		registryDependencies: ["svg-icon"],
	},
	{
		name: "toast-manager",
		module: "@tint-ui/toast-manager",
		withStyles: true,
		icons: ["x", "loader", "toast-success", "toast-info", "toast-warning", "toast-error"],
		registryDependencies: ["svg-icon", "trigger"],
		dependencies: ["sonner"],
	},
	{
		name: "tooltip",
		module: "@tint-ui/tooltip",
		withStyles: true,
	},
	{
		name: "trigger",
		module: "@tint-ui/trigger",
	},
];
